#!/bin/bash

pwshome=$(dirname $(readlink -f "$0"))

set -o pipefail

. "$pwshome/pwdcnf"

"$pwshome"/pwdshow "$@" | tr -d $'\n' | xsel -p

if [ "$?" = 0 ]
then
  echo Ok
else
  echo fail
  exit 1
fi
