#!/bin/bash

pwshome=$(/usr/bin/dirname $(/bin/readlink -f "$0"))

. "$pwshome/pwdcnf"

file=$(/usr/bin/basename $1)
pws_path "$file"

while true
do
  IFS=$'\n'
  read -s -p "Password: " nextpwd0
  echo
  read -s -p "Password (confirm): " nextpwd1
  if [ "$nextpwd0" != "$nextpwd1" ]
  then
    echo "  password mismatch o.O"
  else
    echo
    read -n 1 -p "accept [passwd='$nextpwd0'] [y/N/q]? " take_this
    if [ "$take_this" == "y" ]
    then
      echo
      echo "$nextpwd0" | $gpg_bin --default-recipient $USER --no-verbose --no-for-your-eyes-only -e --output "$pws_path"
      /bin/chmod 600 "$pws_path"
      $pwshome/pwdfor "$file"
      exit 0
    elif [ "$take_this" == "q" ]
    then
      exit 0
    fi
  fi
  echo
done
