#!/bin/bash

pwshome=$(dirname $(readlink -f "$0"))

. "$pwshome/pwdcnf"

file=$(basename "$1")
pws_path "$file"

while true
do
  IFS=$'\n'
  read -s -p "Password: " nextpwd0
  echo
  read -s -p "Password (confirm): " nextpwd1
  if [ "$nextpwd0" != "$nextpwd1" ]
  then
    echo "  password mismatch o.O"
  else
    echo
    echo "$nextpwd0" | gpg --default-recipient $USER --no-verbose --no-for-your-eyes-only -e --output "$pws_path"
    /bin/chmod 600 "$pws_path"
    $pwshome/pwdcopy "$file"
    exit 0
  fi
  echo
done
